import {
  LayoutDashboard,
  Users,
  CalendarDays,
  User,
  UserCog,
  FileBarChart,
  ClipboardCheck,
  FolderKanban,
  ClipboardList,
  PenTool,
  Activity,
} from "lucide-react";

import { Roles } from "../../permissions/roles";
import type { MenuItem } from "../../types/menu";

export const menuItems: MenuItem[] = [
  {
    title: "Dashboard",
    path: "/dashboard",
    icon: LayoutDashboard,
    group: "Principal",
    roles: [
      Roles.ADMIN,
      Roles.ENFERMEIRO,
      Roles.TECNICO_ENFERMAGEM,
      Roles.MEDICO,
      Roles.FISIOTERAPEUTA,
      Roles.NUTRICIONISTA,
      Roles.ASSISTENTE_SOCIAL,
      Roles.RECEPCAO,
    ],
  },
  {
    title: "Residentes",
    path: "/patients",
    icon: Users,
    group: "Atendimento",
    roles: [
      Roles.ADMIN,
      Roles.ENFERMEIRO,
      Roles.TECNICO_ENFERMAGEM,
      Roles.MEDICO,
      Roles.FISIOTERAPEUTA,
      Roles.NUTRICIONISTA,
      Roles.ASSISTENTE_SOCIAL,
  ],
  },
  {
    title: "Evoluções",
    path: "/evolutions",
    icon: ClipboardList,
    group: "Atendimento",
    roles: [
      Roles.ADMIN,
      Roles.ENFERMEIRO,
      Roles.TECNICO_ENFERMAGEM,
      Roles.MEDICO,
      Roles.FISIOTERAPEUTA,
      Roles.NUTRICIONISTA,
      Roles.ASSISTENTE_SOCIAL,
  ],
  },
  {
    title: "Sinais Vitais",
    path: "/vital-signs",
    icon: Activity,
    group: "Atendimento",
    roles: [
      Roles.ADMIN,
      Roles.ENFERMEIRO,
      Roles.TECNICO_ENFERMAGEM,
      Roles.MEDICO,
      Roles.FISIOTERAPEUTA,
      Roles.NUTRICIONISTA,
      Roles.ASSISTENTE_SOCIAL,
  ],
  },
  {
    title: "Agendamentos",
    path: "/appointments",
    icon: CalendarDays,
    group:"Atendimento",
    roles: [
      Roles.ADMIN,
      Roles.ENFERMEIRO,
      Roles.TECNICO_ENFERMAGEM,
      Roles.MEDICO,
      Roles.FISIOTERAPEUTA,
      Roles.NUTRICIONISTA,
      Roles.ASSISTENTE_SOCIAL,
      Roles.RECEPCAO,
    ],
  },
  {
      title: "Documentos",
      path: "/documents",
      icon: FolderKanban,
      group: "Atendimento",
      roles: [
        Roles.ADMIN,
        Roles.ENFERMEIRO,
        Roles.TECNICO_ENFERMAGEM,
        Roles.MEDICO,
        Roles.FISIOTERAPEUTA,
        Roles.NUTRICIONISTA,
        Roles.ASSISTENTE_SOCIAL,
        Roles.RECEPCAO,
      ],
    },
  {
      title: "Assinatura_Digital",
      path: "/assinatura",
      icon: PenTool,
      group: "Atendimento",
      roles: [
        Roles.ADMIN,
        Roles.ENFERMEIRO,
        Roles.TECNICO_ENFERMAGEM,
        Roles.MEDICO,
        Roles.FISIOTERAPEUTA,
        Roles.NUTRICIONISTA,
        Roles.ASSISTENTE_SOCIAL,
       
      ],
    },

  {
    title: "Meu Perfil",
    path: "/perfil",
    icon: User,
    group: "Principal",
    roles: [
      Roles.ADMIN,
      Roles.ENFERMEIRO,
      Roles.TECNICO_ENFERMAGEM,
      Roles.MEDICO,
      Roles.FISIOTERAPEUTA,
      Roles.NUTRICIONISTA,
      Roles.ASSISTENTE_SOCIAL,
      Roles.RECEPCAO,
    ],
  },
  {
    title: "Funcionários",
    path: "/funcionarios",
    icon: UserCog,
    group: "Administração",
    roles: [Roles.ADMIN],
  },
  {
    title: "Relatórios",
    path: "/reports",
    icon: FileBarChart,
    group: "Administração",
    roles: [Roles.ADMIN],
  },
  {
    title: "Auditoria",
    path: "/audit",
    icon: ClipboardCheck,
    group: "Administração",
    roles: [Roles.ADMIN],
  },
];

