import {
  LayoutDashboard,
  Users,
  CalendarDays,
  User,
  UserCog,
  FileBarChart,
  ClipboardCheck,
  FolderKanban,
  ClipboardList,
  PenTool,
  Activity,
  Apple,
} from "lucide-react";

import { Roles } from "../../permissions/roles";
import type { MenuItem } from "../../types/menu";

export const menuItems: MenuItem[] = [
  {
    title: "Dashboard",
    path: "/dashboard",
    icon: LayoutDashboard,
    group: "Principal",
    roles: [
      Roles.COORDENADOR,
      Roles.ENFERMEIRO,
      Roles.TECNICO_ENFERMAGEM,
      Roles.MEDICO,
      Roles.FISIOTERAPEUTA,
      Roles.NUTRICIONISTA,
      Roles.PSICOLOGO,
      Roles.ASSISTENTE_SOCIAL,
      Roles.TERAPEUTA_OCUPACIONAL,
      Roles.FONOAUDIOLOGO,
      Roles.RECEPCAO,
    ],
  },
  {
    title: "Residentes",
    path: "/patients",
    icon: Users,
    group: "Atendimento",
    roles: [
      Roles.COORDENADOR,
      Roles.ENFERMEIRO,
      Roles.TECNICO_ENFERMAGEM,
      Roles.MEDICO,
      Roles.FISIOTERAPEUTA,
      Roles.NUTRICIONISTA,
      Roles.PSICOLOGO,
      Roles.ASSISTENTE_SOCIAL,
      Roles.TERAPEUTA_OCUPACIONAL,
      Roles.FONOAUDIOLOGO,
      Roles.RECEPCAO,
    ],
  },
  {
    title: "Evoluções",
    path: "/evolutions",
    icon: ClipboardList,
    group: "Atendimento",
    roles: [
      Roles.COORDENADOR,
      Roles.ENFERMEIRO,
      Roles.TECNICO_ENFERMAGEM,
      Roles.MEDICO,
      Roles.FISIOTERAPEUTA,
      Roles.NUTRICIONISTA,
      Roles.PSICOLOGO,
      Roles.ASSISTENTE_SOCIAL,
      Roles.TERAPEUTA_OCUPACIONAL,
      Roles.FONOAUDIOLOGO,
    ],
  },
  {
    title: "Nutrição", 
    path: "/nutritional-assessments/today", 
    icon: Apple,
    group: "Atendimento",
    roles: [
      Roles.COORDENADOR,
      Roles.NUTRICIONISTA,
      Roles.ENFERMEIRO,
      Roles.MEDICO,
    ],
  },
  {
    title: "Sinais Vitais",
    path: "/vital-signs",
    icon: Activity,
    group: "Atendimento",
    roles: [
      Roles.COORDENADOR,
      Roles.ENFERMEIRO,
      Roles.TECNICO_ENFERMAGEM,
      Roles.MEDICO,
      Roles.FISIOTERAPEUTA,
      Roles.NUTRICIONISTA,
      Roles.ASSISTENTE_SOCIAL,
    ],
  },
  {
    title: "Agendamentos",
    path: "/appointments",
    icon: CalendarDays,
    group: "Atendimento",
    roles: [
      Roles.COORDENADOR,
      Roles.ENFERMEIRO,
      Roles.TECNICO_ENFERMAGEM,
      Roles.MEDICO,
      Roles.FISIOTERAPEUTA,
      Roles.NUTRICIONISTA,
      Roles.PSICOLOGO,
      Roles.ASSISTENTE_SOCIAL,
      Roles.TERAPEUTA_OCUPACIONAL,
      Roles.FONOAUDIOLOGO,
      Roles.RECEPCAO,
    ],
  },
  {
    title: "Documentos",
    path: "/documents",
    icon: FolderKanban,
    group: "Atendimento",
    roles: [
      Roles.COORDENADOR,
      Roles.ENFERMEIRO,
      Roles.TECNICO_ENFERMAGEM,
      Roles.MEDICO,
      Roles.FISIOTERAPEUTA,
      Roles.NUTRICIONISTA,
      Roles.PSICOLOGO,
      Roles.ASSISTENTE_SOCIAL,
      Roles.TERAPEUTA_OCUPACIONAL,
      Roles.FONOAUDIOLOGO,
      Roles.RECEPCAO,
    ],
  },
  {
    title: "Assinatura_Digital",
    path: "/assinatura",
    icon: PenTool,
    group: "Atendimento",
    roles: [
      Roles.COORDENADOR,
      Roles.ENFERMEIRO,
      Roles.TECNICO_ENFERMAGEM,
      Roles.MEDICO,
      Roles.FISIOTERAPEUTA,
      Roles.NUTRICIONISTA,
      Roles.PSICOLOGO,
      Roles.ASSISTENTE_SOCIAL,
      Roles.TERAPEUTA_OCUPACIONAL,
      Roles.FONOAUDIOLOGO,
    ],
  },
  {
    title: "Meu Perfil",
    path: "/perfil",
    icon: User,
    group: "Principal",
    roles: [
      Roles.ADMIN,
      Roles.COORDENADOR,
      Roles.ENFERMEIRO,
      Roles.TECNICO_ENFERMAGEM,
      Roles.MEDICO,
      Roles.FISIOTERAPEUTA,
      Roles.NUTRICIONISTA,
      Roles.PSICOLOGO,
      Roles.ASSISTENTE_SOCIAL,
      Roles.TERAPEUTA_OCUPACIONAL,
      Roles.FONOAUDIOLOGO,
      Roles.RECEPCAO,
    ],
  },
  {
    title: "Funcionários",
    path: "/funcionarios",
    icon: UserCog,
    group: "Administração",
    roles: [Roles.ADMIN],
  },
  {
    title: "Relatórios",
    path: "/reports",
    icon: FileBarChart,
    group: "Administração",
    roles: [Roles.ADMIN, Roles.COORDENADOR],
  },
  {
    title: "Auditoria",
    path: "/audit",
    icon: ClipboardCheck,
    group: "Administração",
    roles: [Roles.ADMIN, Roles.COORDENADOR],
  },
];